-- Tipo de dato IO -> produce una acción de entrada o salida
--- Haskel busca: main :: IO() 
--- main = putStrLn "String"
--- Unit: no devuelve nada. Sirve para concatenar acciones en un bloque do
-- Con $ se evalúa primero la parte de la derecha y evita colocar paréntesis.
